import { IoCartOutline } from "react-icons/io5";

export const links = [
  { title: "Inicio", href: "/" },
  { title: "Juegos", href: "/juegos" },
  { title: "PlayStation Plus", href: "/playstationplus" },
  { title: "Tarjetas de regalo", href: "/tarjetasderegalo" },
  { title: "Ayuda", href: "/ayuda" },
  { title: "Admin", href: "/admin" },
  { title: <IoCartOutline style={{ fontSize: "1.5rem" }} />, href: "/carrito" },
];

export const paymentMethods = [
  "Mercado Pago",
  "Tarjeta de crédito",
  "Tarjeta de débito",
  "Cryptomonedas",
  "Paypal",
];

export const products = [
  // Suscripciones de PlayStation Plus
  {
    id: "sub1",
    title: "PlayStation Plus Essential - 1 Mes",
    duration: "1 mes",
    price: 10,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },
  {
    id: "sub2",
    title: "PlayStation Plus Essential - 3 Meses",
    duration: "3 meses",
    price: 25,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },
  {
    id: "sub3",
    title: "PlayStation Plus Essential - 12 Meses",
    duration: "12 meses",
    price: 60,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },
  {
    id: "sub4",
    title: "PlayStation Plus Extra - 1 Mes",
    duration: "1 mes",
    price: 15,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },
  {
    id: "sub5",
    title: "PlayStation Plus Extra - 3 Meses",
    duration: "3 meses",
    price: 40,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },
  {
    id: "sub6",
    title: "PlayStation Plus Extra - 12 Meses",
    duration: "12 meses",
    price: 90,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },
  {
    id: "sub7",
    title: "PlayStation Plus Deluxe - 1 Mes",
    duration: "1 mes",
    price: 20,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },
  {
    id: "sub8",
    title: "PlayStation Plus Deluxe - 3 Meses",
    duration: "3 meses",
    price: 50,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },
  {
    id: "sub9",
    title: "PlayStation Plus Deluxe - 12 Meses",
    duration: "12 meses",
    price: 110,
    console: ["ps4", "ps5"],
    category: "subscription",
    imageUrl:
      "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/19/1602364/1685101614000/image_wide.jpg",
  },

  // Tarjetas de Regalo de Steam
  {
    id: "gc1",
    title: "Gift Card Steam $5",
    price: 5,
    region: "arg/usa",
    value: 5,
    category: "giftcard",
    imageUrl: "https://example.com/steam-gift-card-5.jpg",
  },
  {
    id: "gc2",
    title: "Gift Card Steam $10",
    price: 10,
    region: "arg/usa",
    value: 10,
    category: "giftcard",
    imageUrl: "https://example.com/steam-gift-card-10.jpg",
  },
  {
    id: "gc3",
    title: "Gift Card Steam $20",
    price: 20,
    region: "arg/usa",
    value: 20,
    category: "giftcard",
    imageUrl: "https://example.com/steam-gift-card-20.jpg",
  },
  {
    id: "gc4",
    title: "Gift Card Steam $25",
    price: 25,
    region: "arg/usa",
    value: 25,
    category: "giftcard",
    imageUrl: "https://example.com/steam-gift-card-25.jpg",
  },
  {
    id: "gc5",
    title: "Gift Card Steam $50",
    price: 50,
    region: "arg/usa",
    value: 50,
    category: "giftcard",
    imageUrl: "https://example.com/steam-gift-card-50.jpg",
  },
  {
    id: "gc6",
    title: "Gift Card Steam $75",
    price: 75,
    region: "arg/usa",
    value: 75,
    category: "giftcard",
    imageUrl: "https://example.com/steam-gift-card-75.jpg",
  },
  {
    id: "gc7",
    title: "Gift Card Steam $100",
    price: 100,
    region: "arg/usa",
    value: 100,
    category: "giftcard",
    imageUrl: "https://example.com/steam-gift-card-100.jpg",
  },

  // Tarjetas de Regalo de PlayStation
  {
    id: "gc8",
    title: "Gift Card PlayStation $25",
    price: 25,
    region: "usa",
    value: 25,
    category: "giftcard",
    imageUrl: "https://example.com/ps-gift-card-25.jpg",
  },
  {
    id: "gc9",
    title: "Gift Card PlayStation $30",
    price: 30,
    region: "usa",
    value: 30,
    category: "giftcard",
    imageUrl: "https://example.com/ps-gift-card-30.jpg",
  },
  {
    id: "gc10",
    title: "Gift Card PlayStation $50",
    price: 50,
    region: "usa",
    value: 50,
    category: "giftcard",
    imageUrl: "https://example.com/ps-gift-card-50.jpg",
  },
  {
    id: "gc11",
    title: "Gift Card PlayStation $75",
    price: 75,
    region: "usa",
    value: 75,
    category: "giftcard",
    imageUrl: "https://example.com/ps-gift-card-75.jpg",
  },
  {
    id: "gc12",
    title: "Gift Card PlayStation $100",
    price: 100,
    region: "usa",
    value: 100,
    category: "giftcard",
    imageUrl: "https://example.com/ps-gift-card-100.jpg",
  },

  // Juegos Digitales
  {
    id: "game1",
    title: "The Evil Within 2",
    price: 29.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for The Evil Within 2",
    category: "game",
    imageUrl: "/images/games/the_evil_within_2.avif",
  },
  {
    id: "game2",
    title: "FINAL FANTASY® VII",
    price: 39.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for FINAL FANTASY® VII",
    category: "game",
    imageUrl: "/images/games/final_fantasy®_vii.avif",
  },
  {
    id: "game3",
    title: "Fist Of The North Star: Lost Paradise",
    price: 49.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for Fist Of The North Star: Lost Paradise",
    category: "game",
    imageUrl: "/images/games/fist_of_the_north_star:_lost_paradise.avif",
  },
  {
    id: "game4",
    title: "Need for Speed™ Payback",
    price: 59.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for Need for Speed™ Payback",
    category: "game",
    imageUrl: "/images/games/need_for_speed™_payback.avif",
  },
  {
    id: "game5",
    title: "Ultimate Chicken Horse",
    price: 69.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for Ultimate Chicken Horse",
    category: "game",
    imageUrl: "/images/games/ultimate_chicken_horse.avif",
  },
  {
    id: "game6",
    title: "Five Nights at Freddy's",
    price: 29.99,
    accountType: "secondary",
    console: ["ps4", "ps5"],
    description: "Description for Five Nights at Freddy's",
    category: "game",
    imageUrl: "/images/games/five_nights_at_freddy's.avif",
  },
  {
    id: "game7",
    title: "Goat Simulator",
    price: 39.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for Goat Simulator",
    category: "game",
    imageUrl: "/images/games/goat_simulator.avif",
  },
  {
    id: "game8",
    title: "Tom Clancy’s Ghost Recon® Wildlands - Standard Edition",
    price: 49.99,
    accountType: "secondary",
    console: ["ps5"],
    description:
      "Description for Tom Clancy’s Ghost Recon® Wildlands - Standard Edition",
    category: "game",
    imageUrl:
      "/images/games/tom_clancy’s_ghost_recon®_wildlands_-_standard_edition.avif",
  },
  {
    id: "game9",
    title: "Anthem",
    price: 59.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for Anthem",
    category: "game",
    imageUrl: "/images/games/anthem.avif",
  },
  {
    id: "game10",
    title: "Gravity Rush 2",
    price: 69.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for Gravity Rush 2",
    category: "game",
    imageUrl: "/images/games/gravity_rush_2.avif",
  },
  {
    id: "game11",
    title: "Immortal Fenix Rising PS4 & PS5",
    price: 29.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for Immortal Fenix Rising PS4 & PS5",
    category: "game",
    imageUrl: "/images/games/immortal_fenix_rising_ps4_&_ps5.avif",
  },
  {
    id: "game12",
    title: "Persona Dancing: Endless Night Collection",
    price: 39.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for Persona Dancing: Endless Night Collection",
    category: "game",
    imageUrl: "/images/games/persona_dancing:_endless_night_collection.avif",
  },
  {
    id: "game13",
    title: "The Division 2",
    price: 49.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for The Division 2",
    category: "game",
    imageUrl: "/images/games/the_division_2.avif",
  },
  {
    id: "game14",
    title: "THE KING OF FIGHTERS 2000",
    price: 59.99,
    accountType: "secondary",
    console: ["ps4", "ps5"],
    description: "Description for THE KING OF FIGHTERS 2000",
    category: "game",
    imageUrl: "/images/games/the_king_of_fighters_2000.avif",
  },
  {
    id: "game15",
    title: "RESIDENT EVIL 5",
    price: 69.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for RESIDENT EVIL 5",
    category: "game",
    imageUrl: "/images/games/resident_evil_5.avif",
  },
  {
    id: "game16",
    title: "The Evil Within",
    price: 29.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for The Evil Within",
    category: "game",
    imageUrl: "/images/games/the_evil_within.avif",
  },
  {
    id: "game17",
    title: "WRC 8 Deluxe Edition FIA World Rally Championship",
    price: 39.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description:
      "Description for WRC 8 Deluxe Edition FIA World Rally Championship",
    category: "game",
    imageUrl:
      "/images/games/wrc_8_deluxe_edition_fia_world_rally_championship.avif",
  },
  {
    id: "game18",
    title: "Mortal Kombat 11",
    price: 49.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for Mortal Kombat 11",
    category: "game",
    imageUrl: "/images/games/mortal_kombat_11.avif",
  },
  {
    id: "game19",
    title: "Mafia III: Definitive Edition",
    price: 59.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for Mafia III: Definitive Edition",
    category: "game",
    imageUrl: "/images/games/mafia_iii:_definitive_edition.avif",
  },
  {
    id: "game20",
    title: "SONIC FORCES™",
    price: 69.99,
    accountType: "secondary",
    console: ["ps4", "ps5"],
    description: "Description for SONIC FORCES™",
    category: "game",
    imageUrl: "/images/games/sonic_forces™.avif",
  },
  {
    id: "game21",
    title: "WWE 2k20",
    price: 29.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for WWE 2k20",
    category: "game",
    imageUrl: "/images/games/wwe_2k20.avif",
  },
  {
    id: "game22",
    title: "RESIDENT EVIL 7 biohazard",
    price: 39.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for RESIDENT EVIL 7 biohazard",
    category: "game",
    imageUrl: "/images/games/resident_evil_7_biohazard.avif",
  },
  {
    id: "game23",
    title: "The Evil Within 2",
    price: 49.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for The Evil Within 2",
    category: "game",
    imageUrl: "/images/games/the_evil_within_2.avif",
  },
  {
    id: "game24",
    title: "Batman: Arkham Collection",
    price: 59.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for Batman: Arkham Collection",
    category: "game",
    imageUrl: "/images/games/batman:_arkham_collection.avif",
  },
  {
    id: "game25",
    title: "Red Dead Redemption 2: Ultimate Edition",
    price: 69.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for Red Dead Redemption 2: Ultimate Edition",
    category: "game",
    imageUrl: "/images/games/red_dead_redemption_2:_ultimate_edition.avif",
  },
  {
    id: "game26",
    title: "Mortal Kombat 11 Ultimate",
    price: 29.99,
    accountType: "secondary",
    console: ["ps4", "ps5"],
    description: "Description for Mortal Kombat 11 Ultimate",
    category: "game",
    imageUrl: "/images/games/mortal_kombat_11_ultimate.avif",
  },
  {
    id: "game27",
    title: "Watch Dogs®: Legion PS4 & PS5",
    price: 39.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for Watch Dogs®: Legion PS4 & PS5",
    category: "game",
    imageUrl: "/images/games/watch_dogs®:_legion_ps4_&_ps5.avif",
  },
  {
    id: "game28",
    title: "Overcooked! 2",
    price: 49.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for Overcooked! 2",
    category: "game",
    imageUrl: "/images/games/overcooked!_2.avif",
  },
  {
    id: "game29",
    title: "RESIDENT EVIL 2",
    price: 59.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for RESIDENT EVIL 2",
    category: "game",
    imageUrl: "/images/games/resident_evil_2.avif",
  },
  {
    id: "game30",
    title: "NARUTO SHIPPUDEN: Ultimate Ninja STORM 4",
    price: 69.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for NARUTO SHIPPUDEN: Ultimate Ninja STORM 4",
    category: "game",
    imageUrl: "/images/games/naruto_shippuden:_ultimate_ninja_storm_4.avif",
  },
  {
    id: "game31",
    title: "NBA 2K24 Kobe Bryant Edition for PS4™",
    price: 29.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for NBA 2K24 Kobe Bryant Edition for PS4™",
    category: "game",
    imageUrl: "/images/games/nba_2k24_kobe_bryant_edition_for_ps4™.avif",
  },
  {
    id: "game32",
    title: "The Callisto Protocol™",
    price: 39.99,
    accountType: "secondary",
    console: ["ps4", "ps5"],
    description: "Description for The Callisto Protocol™",
    category: "game",
    imageUrl: "/images/games/the_callisto_protocol™.avif",
  },
  {
    id: "game33",
    title: "Assassin's Creed® Odyssey",
    price: 49.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for Assassin's Creed® Odyssey",
    category: "game",
    imageUrl: "/images/games/assassin's_creed®_odyssey.avif",
  },
  {
    id: "game34",
    title: "Sonic Colours: Ultimate",
    price: 59.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for Sonic Colours: Ultimate",
    category: "game",
    imageUrl: "/images/games/sonic_colours:_ultimate.avif",
  },
  {
    id: "game35",
    title: "Call of Duty®: Vanguard - PS4",
    price: 69.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for Call of Duty®: Vanguard - PS4",
    category: "game",
    imageUrl: "/images/games/call_of_duty®:_vanguard_-_ps4.avif",
  },
  {
    id: "game36",
    title: "The Last Of Us™ Remastered",
    price: 29.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for The Last Of Us™ Remastered",
    category: "game",
    imageUrl: "/images/games/the_last_of_us™_remastered.avif",
  },
  {
    id: "game37",
    title: "Grand Theft Auto V (PlayStation®5)",
    price: 39.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for Grand Theft Auto V (PlayStation®5)",
    category: "game",
    imageUrl: "/images/games/grand_theft_auto_v_(playstation®5).avif",
  },
  {
    id: "game38",
    title: "Minecraft",
    price: 49.99,
    accountType: "secondary",
    console: ["ps4", "ps5"],
    description: "Description for Minecraft",
    category: "game",
    imageUrl: "/images/games/minecraft.avif",
  },
  {
    id: "game39",
    title: "EA SPORTS™ FIFA 23 Standard Edition PS4™",
    price: 59.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for EA SPORTS™ FIFA 23 Standard Edition PS4™",
    category: "game",
    imageUrl: "/images/games/ea_sports™_fifa_23_standard_edition_ps4™.avif",
  },
  {
    id: "game40",
    title: "SnowRunner",
    price: 69.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for SnowRunner",
    category: "game",
    imageUrl: "/images/games/snowrunner.avif",
  },
  {
    id: "game41",
    title: "Call of Duty®: Ghosts Gold Edition",
    price: 29.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for Call of Duty®: Ghosts Gold Edition",
    category: "game",
    imageUrl: "/images/games/call_of_duty®:_ghosts_gold_edition.avif",
  },
  {
    id: "game42",
    title: "RACCOON CITY EDITION",
    price: 39.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for RACCOON CITY EDITION",
    category: "game",
    imageUrl: "/images/games/raccoon_city_edition.avif",
  },
  {
    id: "game43",
    title: "Ghost of Tsushima DIRECTOR’S CUT PS4",
    price: 49.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for Ghost of Tsushima DIRECTOR’S CUT PS4",
    category: "game",
    imageUrl: "/images/games/ghost_of_tsushima_director’s_cut_ps4.avif",
  },
  {
    id: "game44",
    title: "Horizon Forbidden West™ PS4 & PS5",
    price: 59.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for Horizon Forbidden West™ PS4 & PS5",
    category: "game",
    imageUrl: "/images/games/horizon_forbidden_west™_ps4_&_ps5.avif",
  },
  {
    id: "game45",
    title: "Ghost of Tsushima DIRECTOR’S CUT PS5",
    price: 69.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for Ghost of Tsushima DIRECTOR’S CUT PS5",
    category: "game",
    imageUrl: "/images/games/ghost_of_tsushima_director’s_cut_ps5.avif",
  },
  {
    id: "game46",
    title: "God of War Ragnarök PS4 & PS5",
    price: 29.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for God of War Ragnarök PS4 & PS5",
    category: "game",
    imageUrl: "/images/games/god_of_war_ragnarök_ps4_&_ps5.avif",
  },
  {
    id: "game47",
    title: "Marvel's Spider-Man: Miles Morales PS4 & PS5",
    price: 39.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for Marvel's Spider-Man: Miles Morales PS4 & PS5",
    category: "game",
    imageUrl: "/images/games/marvel's_spider-man:_miles_morales_ps4_&_ps5.avif",
  },
  {
    id: "game48",
    title: "UNCHARTED™ 4: A Thief’s End",
    price: 49.99,
    accountType: "secondary",
    console: ["ps4", "ps5"],
    description: "Description for UNCHARTED™ 4: A Thief’s End",
    category: "game",
    imageUrl: "/images/games/uncharted™_4:_a_thief’s_end.avif",
  },
  {
    id: "game49",
    title: "Gran Turismo® 7 PS4 & PS5",
    price: 59.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for Gran Turismo® 7 PS4 & PS5",
    category: "game",
    imageUrl: "/images/games/gran_turismo®_7_ps4_&_ps5.avif",
  },
  {
    id: "game50",
    title: "The Last of Us™ Part I",
    price: 69.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for The Last of Us™ Part I",
    category: "game",
    imageUrl: "/images/games/the_last_of_us™_part_i.avif",
  },
  {
    id: "game51",
    title: "DEATH STRANDING DIRECTOR'S CUT",
    price: 29.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for DEATH STRANDING DIRECTOR'S CUT",
    category: "game",
    imageUrl: "/images/games/death_stranding_director's_cut.avif",
  },
  {
    id: "game52",
    title: "NARUTO SHIPPUDEN: Ultimate Ninja STORM 4 ROAD TO BORUTO",
    price: 39.99,
    accountType: "secondary",
    console: ["ps4"],
    description:
      "Description for NARUTO SHIPPUDEN: Ultimate Ninja STORM 4 ROAD TO BORUTO",
    category: "game",
    imageUrl:
      "/images/games/naruto_shippuden:_ultimate_ninja_storm_4_road_to_boruto.avif",
  },
  {
    id: "game53",
    title: "ONE PIECE ODYSSEY",
    price: 49.99,
    accountType: "primary",
    console: ["ps5"],
    description: "Description for ONE PIECE ODYSSEY",
    category: "game",
    imageUrl: "/images/games/one_piece_odyssey.avif",
  },
  {
    id: "game54",
    title: "One Piece: Pirate Warriors 4",
    price: 59.99,
    accountType: "secondary",
    console: ["ps4", "ps5"],
    description: "Description for One Piece: Pirate Warriors 4",
    category: "game",
    imageUrl: "/images/games/one_piece:_pirate_warriors_4.avif",
  },
  {
    id: "game55",
    title: "STREET FIGHTER™ V",
    price: 69.99,
    accountType: "primary",
    console: ["ps4"],
    description: "Description for STREET FIGHTER™ V",
    category: "game",
    imageUrl: "/images/games/street_fighter™_v.avif",
  },
  {
    id: "game56",
    title: "TEKKEN 7",
    price: 29.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for TEKKEN 7",
    category: "game",
    imageUrl: "/images/games/tekken_7.avif",
  },
  {
    id: "game57",
    title: "eFootball PES 2021 SEASON UPDATE",
    price: 39.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for eFootball PES 2021 SEASON UPDATE",
    category: "game",
    imageUrl: "/images/games/efootball_pes_2021_season_update.avif",
  },
  {
    id: "game58",
    title: "Bloodborne™",
    price: 49.99,
    accountType: "secondary",
    console: ["ps4"],
    description: "Description for Bloodborne™",
    category: "game",
    imageUrl: "/images/games/bloodborne™.avif",
  },
  {
    id: "game59",
    title: "DEAD RISING",
    price: 59.99,
    accountType: "primary",
    console: ["ps4", "ps5"],
    description: "Description for DEAD RISING",
    category: "game",
    imageUrl: "/images/games/dead_rising.avif",
  },
  {
    id: "game60",
    title: "BORDERLANDS 3 PS4 & PS5",
    price: 69.99,
    accountType: "secondary",
    console: ["ps5"],
    description: "Description for BORDERLANDS 3 PS4 & PS5",
    category: "game",
    imageUrl: "/images/games/borderlands_3_ps4_&_ps5.avif",
  },
];
